name: workHive
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  simple_animations: ^1.3.3
  http: ^0.13.4
  toast: ^0.3.0
  fluttertoast: ^8.0.9
  select_form_field: ^2.2.0
  google_fonts: ^3.0.1
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  dropdown_button2: ^1.6.2
  hexcolor: ^2.0.7
  flutter_svg: ^1.1.0
  pinput: ^2.2.11
  badges: ^2.0.3
  numeral: ^2.0.1
  intl: ^0.17.0
  dotted_border: ^2.0.0+2
  url_launcher: ^6.1.5
  phlox_animations: ^2.1.1
  screenshot: ^1.2.3
  shimmer: ^2.0.0
  pdf: ^3.8.1
  printing: ^5.9.1
  bottom_indicator_bar: ^2.0.0
  flutter_rounded_date_picker: ^3.0.2




    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pointycastle: ^3.6.2
  encrypt: ^5.0.1
  flutter_localizations:
    sdk: flutter
  scoped_model: ^2.0.0
  conditional_builder_null_safety: ^0.0.6
  localstorage: ^4.0.0+1
  steel_crypt: ^3.0.0+1
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/workhive.png"
  image_path_android: "assets/images/workhive.png"


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/lancher/lancher.png
